### ISSUE TITLE
Create a UI mockup for how the android application should look like

### ISSUE THREAD

**Issue by adam-gligor** [4it2017/docs#10]
Create sketches to illustrate how the android application should look like. 

- The types of screens 
- The layout for each screen 
- Save the result in the repository's docs folder

Tip: use an online sketching application like gliffy or draw.io or one of your choice.

**Comment by AndreicaPaul** [comment]
https://www.fluidui.com/editor/live/comment/cF82cDBjTmU3RTkxSGFORVZSQVZUY0NEZkExTWgyWDdheA==

Quick preview on the main screen

**Comment by adam-gligor** [comment]
For the main screen we can take ideas from existing weather station devices. Here's one that displays similar data to what we will have. [link](https://s5emagst.akamaized.net/products/421/420345/images/res_d5f82251ba1a4097ee1b786dc6312bd9_full.jpg)

 - Time, date, week of the day
 - Current temperature and humidity 
 - Evolution of atmospheric pressure over the last 12 hours
 - Weather forecast using a picture

Let's discuss this the next meeting
